name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: go test ./...
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install opa
      - run: opa test ./policies/...
      - run: go build -o opa-policies .
      - run: ./opa-policies validate examples/k8s/bad-pod.yaml
      - run: ./opa-policies validate examples/docker/bad.Dockerfile
      - run: ./opa-policies validate examples/terraform/bad-aws.tf
      - run: ./opa-policies validate examples/github/bad-workflow.yaml
